services:
  - type: web
    name: lms-app
    runtime: python
    buildCommand: >
      pip install -r requirements.txt &&
      cd pr1 &&
      python manage.py migrate
    startCommand: cd pr1 && gunicorn pr1.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: DJANGO_SETTINGS_MODULE
        value: pr1.settings
      - key: DEBUG
        value: "False"
