# Generated by Django 5.2.5 on 2025-10-10 05:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanner', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('publisher', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('abstract', models.TextField(null=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=200)),
                ('book_id', models.CharField(max_length=100)),
                ('book_name', models.CharField(max_length=200)),
                ('borrowed_at', models.DateTimeField(auto_now_add=True)),
                ('returned', models.BooleanField(default=False)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('borrow_duration_days', models.IntegerField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('is_overdue', models.BooleanField(default=False)),
                ('overdue_days', models.IntegerField(default=0)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
            options={
                'db_table': 'borrow_records',
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=200)),
                ('book_id', models.CharField(max_length=100)),
                ('book_name', models.CharField(max_length=200)),
                ('borrowed_at', models.DateTimeField(auto_now_add=True)),
                ('returned', models.BooleanField(default=False)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('borrow_duration_days', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'borrow_record_table',
            },
        ),
        migrations.CreateModel(
            name='CollegeStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100, unique=True)),
                ('student_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanner', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('publisher', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HODUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hod_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=200)),
                ('book_id', models.CharField(max_length=100)),
                ('book_name', models.CharField(max_length=200)),
                ('borrowed_at', models.DateTimeField(auto_now_add=True)),
                ('returned', models.BooleanField(default=False)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('borrow_duration_days', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'main_exam',
            },
        ),
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('DinaThanthi', 'Dina Thanthi'), ('Dinamalar', 'Dina Malar'), ('TheHindu', 'The Hindu'), ('IndianExpress', 'Indian Express'), ('Dinamani', 'Dina Mani')], max_length=50)),
                ('language', models.CharField(choices=[('TA', 'Tamil'), ('EN', 'English')], max_length=20)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to='newspapers/')),
            ],
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_email', models.EmailField(max_length=254, unique=True)),
                ('student_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HODMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read', models.BooleanField(default=False)),
                ('hod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hoduser')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hod_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('book_title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=150, null=True)),
                ('publisher', models.CharField(blank=True, max_length=150, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('hod_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.hoduser')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('main_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subexams', to='myapp.mainexam')),
            ],
            options={
                'db_table': 'sub_exam',
            },
        ),
    ]
