# Generated by Django 5.2.5 on 2025-10-10 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_is_active_student_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_password',
            new_name='password',
        ),
    ]
