# Generated by Django 5.2.5 on 2025-10-14 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_donation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_password',
            new_name='password',
        ),
    ]
