# Generated by Django 5.2.5 on 2025-10-10 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_student_password_student_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='password',
            new_name='student_password',
        ),
    ]
