# Generated by Django 5.2.5 on 2025-10-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_password_student_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanner_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('available', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10)),
                ('donor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('donor_type', models.CharField(blank=True, max_length=100, null=True)),
                ('donor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('donor_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('donor_id', models.CharField(blank=True, max_length=100, null=True)),
                ('donation_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
